### PR TITLE
Add Context Typescript Example

### PR DESCRIPTION
**Pull request by codyaverett**
Add typescript example of using context adapted with typings from my previous example before official typescript support.

For typescript example support I changed examples/index.js to a .tsx extension.
JS component examples still work

To ease future additions of examples I created a simple array of tuples that can be used to map a route to a component example.

```// Route to Component mapping
// [0] Name and Route
// [1] Component
const routeMap: [string, React.ReactNode][] = [
  ['Counter', Counter],
  ['ContextCounter', ContextCounter]
];
```

Also, i placed the list and Example renderings in a flex container to better separate the example from the list.

I'm interested to help more on examples and making this look and function better.
I'm thinking along the lines of something much simpler than, but similar to [Storybook](https://storybook.js.org/)?

@diegohaz feedback?  Also, am I using `ComposableContainer` typing properly?

capture

### CODE REVIEW

**Comment by codyaverett** [comment]
Linting is failing with `Multiline support is limited to browsers supporting ES5 only` This is being thrown when i use `<></>` react fragment shorthand.

**Comment by diegohaz** [comment]
Great job, @codyaverett. Thank you very much.

The eslint issue seems to be related to https://github.com/eslint/typescript-eslint-parser/issues/503

I'm OK for disabling that rule for typescript in the meanwhile.

> I'm interested to help more on examples and making this look and function better.
> I'm thinking along the lines of something much simpler than, but similar to Storybook?

That would be really good. 😍

> Also, am I using ComposableContainer typing properly?

Yes, I'd only put `{...props}` before and merge `initialState`, like this:
```jsx
<Container {...props} initialState={{ ...initialState, ...props.initialState }} />
```

Tell me when you're done so I can merge it. 😉

**Comment by codyaverett** [comment]
@diegohaz

Thanks for the suggestion on merging the initialState.  

Also, I went ahead and just used <React.Fragment> instead of the shorthand.  If you'd rather disable the linting rule I can do that.

Otherwise, it's done.

**Comment by codyaverett** [comment]
Prettier is at it again. 🗡

**Comment by codyaverett** [comment]
@diegohaz Do you have a prettier config we can add?

**Comment by diegohaz** [comment]
I [just use prettier (tm)](https://twitter.com/diegohaz/status/979575014155530240) haha

I have a configuration on my VSCode that runs `eslint --fix` on save. But I think we should definitely add a precommit hook like we did on ReaKit: https://github.com/reakit/reakit/blob/master/package.json#L25-L35

**Comment by codyaverett** [comment]
Cool, good to know.  I've just been using TSlint + my own Prettier prior to now in my own projects.  
`eslint --fix` didn't seem to fix anything for me 😭 I'll have to look into what's up with my VScode setup sometime this weekend.

**Comment by diegohaz** [comment]
You can also run `npm run lint -- --fix` (or `yarn lint --fix`) to fix formatting eslint errors, like prettier ones, automatically.

**Pull request merged**
