### PR TITLE
Allow React 17 as a peerDependency

### PR DESCRIPTION
**Pull request by jamesplease**
React 17 [was released today](https://reactjs.org/blog/2020/10/20/react-v17.html). I haven't yet tested constate with this new release, but there's a good chance that it'll work just fine.

### CODE REVIEW

**Review by diegohaz — APPROVED** [review]
Thanks @jamesplease!

**Comment by Favna** [comment]
Came here because I'm updating my package.json right now but why not just specify it as `"react": ">=16.8"`?

**Comment by jamesplease** [comment]
It’s just a matter of preference. Let’s say we specify what you suggested, `”react”: “>=16.8”`. Should React 18 come out with changes that break constate, then the dependency list is not accurate, and a new release would need to be published that puts an upper limit on the dependency. Issues may be opened up by users who are confused and who expect the library to work with the new release.

Of course, if constate continues to work just fine in 18, then specifying the dependencies that way is quite convenient.

With the approach in this PR, the maintainers must manually update the dependency for each major release. The downside, as we have seen, is that backwards compatible major releases require a version bump.

I have a slight preference for being “honest” with the dependencies array. Will constate work with React 18? Who knows. Maybe, maybe not. But we do know that it works with 16.8+ and 17, and the dependency array reflects what we do know.

With that said, I don’t have a strong preference either way, so if @diegohaz prefers to make it `>=16.8` then that’s A-OK by me.

**Comment by Favna** [comment]
Your reasoning is perfectly sound. The version bump is pretty okay to do anyway.

**Pull request merged**
