### PR TITLE
fix: Fix `React.FC` types for React 18

### PR DESCRIPTION
**Pull request by mikestopcontinues**
New `FC` type no longer includes `{children}`. This fixes that.

### CODE REVIEW

**Comment by diegohaz** [comment]
Thanks! I'll take a look into what's happening with Travis as it's not running the tests.

**Comment by Andrey-Bazhanov** [comment]
@mikestopcontinues can you please fix linter and push again?

**Comment by mikestopcontinues** [comment]
@diegohaz - Not sure if you'll get notified of the updated branch. I need new approval for the ci/cd workflow.

**Review by diegohaz — APPROVED** [review]
Nice! Thank you!

**Pull request merged**
